### ISSUE TITLE
Keybinding request: execute request

### ISSUE THREAD

**Issue by damylen** [jcoc611/vsconnect#8]
Great work! Would it be possible to add a keybinding for executing a request, even when you are working in another file. I'm testing a post using a JSON file. Would really speed up the testing if I can simply edit the JSON file and with a simple key-stroke VSConnect can make the request.

**Comment by jcoc611** [comment]
Thanks for the feedback, and sorry for the long delay. I finally got around to adding a command for this. You can add something like this to your `keybindings.json`:

```json
{"key": "ctrl+shift+/", "command": "vsConnectClient.sendCurrentRequest" }
```
